apiVersion: v1
kind: ConfigMap
metadata:
  name: authproxy-routes
  namespace: agentic-ml
data:
  routes.yaml: |
    - host: "model-registry*"
      target_audience: "spiffe://localtest.me/ns/agentic-ml/sa/model-registry"
      token_scopes: "openid read:features write:model-registry"
    - host: "data-agent*"
      target_audience: "spiffe://localtest.me/ns/agentic-ml/sa/data-agent"
      token_scopes: "openid read:features"
    - host: "training-agent*"
      target_audience: "spiffe://localtest.me/ns/agentic-ml/sa/training-agent"
      token_scopes: "openid write:model-registry provision:gpu"
    - host: "eval-agent*"
      target_audience: "spiffe://localtest.me/ns/agentic-ml/sa/eval-agent"
      token_scopes: "openid read:test-data"
    - host: "deploy-agent*"
      target_audience: "spiffe://localtest.me/ns/agentic-ml/sa/deploy-agent"
      token_scopes: "openid deploy:staging"
