apiVersion: v1
kind: Namespace
metadata:
  name: agentic-ml
  labels:
    demo: pytorch-conf-2026
    mode: agentic
    istio-discovery: enabled
    shared-gateway-access: "true"
    kagenti-enabled: "true"
